apiVersion: v1 
kind: Service 
metadata:
  name: mysql-servioce
spec:
   #loadbalancer clusterip
  selector:
    app: mysql 
  ports: 
    - name: mysql  
      port: 3306
  clusterIP: None #internally kubernetes will ensure that the pod is accessable using pod ip