apiVersion: v1 
kind: Service 
metadata:
  name: usermgmt-webapp
spec:
   #loadbalancer clusterip
   type: LoadBalancer
  selector:
    app: usermgmt-webapp

  ports: 
    - port: 80
      targetPort: 8080
  